=== fancige/demo/bbs/data/users/userlist.dtd
<!ELEMENT userlist (user*)>
<!ELEMENT user (userid, username, password)>
<!ELEMENT userid (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>

=== fancige/demo/bbs/data/users/userlist.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE userlist SYSTEM "userlist.dtd">
<userlist>
    <user>
        <userid>111111</userid>
        <username>fancige</username>
        <password>123456</password>
    </user>
    <user>
        <userid>734548</userid>
        <username>wakada</username>
        <password>123456</password>
    </user>
</userlist>
