=== fancige/demo/chat2/data/MainFrame.dtd
<!ELEMENT root (component*)>
<!ELEMENT component (class, var, insets?, rectangle?, color?)>

<!ELEMENT class (#PCDATA)>
<!ELEMENT var (#PCDATA)>

<!ELEMENT insets (top, left, bottom, right)>
<!ELEMENT top (#PCDATA)>
<!ELEMENT left (#PCDATA)>
<!ELEMENT bottom (#PCDATA)>
<!ELEMENT right (#PCDATA)>

<!ELEMENT rectangle (x, y, width, height)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>

<!ELEMENT color (background?, focus?)>
<!ELEMENT background (red, green, blue)>
<!ELEMENT focus (red, green, blue)>
<!ELEMENT red (#PCDATA)>
<!ELEMENT green (#PCDATA)>
<!ELEMENT blue (#PCDATA)>

=== fancige/demo/chat2/data/MainFrame.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "MainFrame.dtd">
<root>
	<component>
		<class>javax.swing.JPanel</class>
		<var>rootPanel</var>
		<rectangle>
			<x>0</x>
			<y>0</y>
			<width>230</width>
			<height>550</height>
		</rectangle>
		<color>
			<background>
				<red>255</red>
				<green>255</green>
				<blue>255</blue>
			</background>
		</color>
	</component>
	<component>
		<class>javax.swing.JPanel</class>
		<var>topPanel</var>
		<rectangle>
			<x>0</x>
			<y>0</y>
			<width>230</width>
			<height>100</height>
		</rectangle>
		<color>
			<background>
				<red>225</red>
				<green>230</green>
				<blue>246</blue>
			</background>
		</color>
	</component>
	<component>
		<class>javax.swing.JScrollPane</class>
		<var>middlePane</var>
		<rectangle>
			<x>0</x>
			<y>100</y>
			<width>0</width>
			<height>0</height>
		</rectangle>
	</component>
	<component>
		<class>javax.swing.JPanel</class>
		<var>bottomPanel</var>
		<rectangle>
			<x>0</x>
			<y>550</y>
			<width>230</width>
			<height>50</height>
		</rectangle>
		<color>
			<background>
				<red>225</red>
				<green>230</green>
				<blue>246</blue>
			</background>
		</color>
	</component>
	<component>
		<class>javax.swing.JLabel</class>
		<var>parentLabel</var>
		<insets>
			<top>2</top>
			<left>6</left>
			<bottom>2</bottom>
			<right>6</right>
		</insets>
		<rectangle>
			<x>0</x>
			<y>0</y>
			<width>0</width>
			<height>30</height>
		</rectangle>
		<color>
			<background>
				<red>224</red>
				<green>234</green>
				<blue>248</blue>
			</background>
			<focus>
				<red>207</red>
				<green>215</green>
				<blue>241</blue>
			</focus>
		</color>
	</component>
	<component>
		<class>javax.swing.JLabel</class>
		<var>childLabel</var>
		<insets>
			<top>2</top>
			<left>6</left>
			<bottom>2</bottom>
			<right>6</right>
		</insets>
		<rectangle>
			<x>0</x>
			<y>0</y>
			<width>0</width>
			<height>50</height>
		</rectangle>
		<color>
			<background>
				<red>255</red>
				<green>255</green>
				<blue>255</blue>
			</background>
			<focus>
				<red>237</red>
				<green>240</green>
				<blue>220</blue>
			</focus>
		</color>
	</component>
</root>
